Repository Badger-Finance/badger-subgraph, pull requests merged in 2022-03, with the labels that each got.

#35 chore: add strategy balance
  src/badger-across/package.json
  src/badger-nfts/package.json
  src/fuse-subgraph/package.json
  src/vaults/LICENSE
  src/vaults/README.md
  src/vaults/abis/BadgerAffiliateSett.json
  src/vaults/abis/BadgerController.json
  src/vaults/abis/BadgerSett.json
  src/vaults/abis/BadgerSettV1_5.json
  src/vaults/abis/BadgerSettV2.json
  src/vaults/abis/BadgerStrategy.json
  src/vaults/abis/Digg.json
  src/vaults/abis/ERC20.json
  src/vaults/abis/VaultRegistry.json
  src/vaults/config/arbitrum.json
  src/vaults/config/avalanche.json
  src/vaults/config/bsc.json
  src/vaults/config/fantom.json
  src/vaults/config/mainnet.json
  src/vaults/config/matic.json
  src/vaults/config/xdai.json
  src/vaults/package.json
  src/vaults/schema.graphql
  src/vaults/src/constants.ts
  src/vaults/src/entities/affiliate-sett.ts
  src/vaults/src/entities/badger-sett-v2.ts
  src/vaults/src/entities/badger-sett.ts
  src/vaults/src/entities/badger-tree-distribution.ts
  src/vaults/src/entities/contracts.ts
  src/vaults/src/entities/controller.ts
  src/vaults/src/entities/harvest.ts
  src/vaults/src/entities/registry.ts
  src/vaults/src/entities/sett-snapshot.ts
  src/vaults/src/entities/strategy.ts
  src/vaults/src/entities/token.ts
  src/vaults/src/entities/transaction.ts
  src/vaults/src/entities/transfer.ts
  src/vaults/src/entities/user-sett-balance.ts
  src/vaults/src/entities/user.ts
  src/vaults/src/handlers/registry-handler.ts
  src/vaults/src/handlers/sett-affiliate-handler.ts
  src/vaults/src/handlers/sett-handler.ts
  src/vaults/src/handlers/sett-v1-5-handler.ts
  src/vaults/src/handlers/sett-v2-handler.ts
  src/vaults/src/handlers/strategy-handler.ts
  src/vaults/subgraph.template.yaml
  src/vaults/tsconfig.json
Labels: enhancement

#37 Vaults 1.5
  src/vaults/abis/BadgerStrategyV1_5.json
  src/vaults/src/constants.ts
  src/vaults/src/entities/badger-sett-v1-5.ts
  src/vaults/src/entities/badger-tree-distribution.ts
  src/vaults/src/entities/harvest.ts
  src/vaults/src/entities/strategy.ts
  src/vaults/src/handlers/registry-handler.ts
  src/vaults/src/handlers/sett-v1-5-handler.ts
  src/vaults/src/handlers/sett-v2-handler.ts
  src/vaults/src/handlers/strategy-handler.ts
  src/vaults/subgraph.template.yaml
Labels: ON HODL

#40 fix: add version to sett and fix strategy version
  src/vaults/schema.graphql
  src/vaults/src/constants.ts
  src/vaults/src/entities/badger-sett-v1-5.ts
  src/vaults/src/entities/badger-sett-v2.ts
  src/vaults/src/entities/badger-sett.ts
  src/vaults/src/entities/harvest.ts
  src/vaults/src/entities/strategy.ts
  src/vaults/src/handlers/registry-handler.ts
  src/vaults/src/handlers/sett-handler.ts
  src/vaults/src/handlers/sett-v1-5-handler.ts
Labels: bug
